name: CS-Fixer

on:
  push:
    branches:
      - main
    paths:
      - '**.php'
  pull_request:
  workflow_dispatch:

jobs:
  cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none

      - name: Install dependencies
        run: composer install

      - name: Run PHP-CS-Fixer
        run: vendor/bin/php-cs-fixer fix --dry-run
